name = "BulkaSKorizei"
author = "4eburek"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "919df48b0d5df7042cd0db480df93ce2346ec10af31662b0d5b039f151bb0609"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.105"

[options]
acceptable-game-versions = []
datapack-folder = "config/openloader/data"
