name = "Cargocraft"
author = "4eburek"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd33cd6e75c20160440974b0f6af2e1d83b83ee8aa3942321510827939f2fa34"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.103"
