name = "Cargocraft"
author = "Humanised doll"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e58d8200c498fecb27ca54b06ec7bd5b97b6a8c3c4d47204400a84fbac332eba"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
