name = "Cargocraft"
author = "Humanised doll"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24f2129d1de8cb7c965eff8a7f12c782c19d605dae0f174e864447786eb6b0ff"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
datapack-folder = "datapacks"
