StartupEvents.registry('item', event => {
    let mechanism = (name, rarity) => {
		let id = name.toLowerCase()
		event.create(id + '_mechanism').texture("kubejs:item/" + id + "_mechanism").displayName(name + ' Mechanism').rarity(rarity ? rarity : 'COMMON')
		event.create('incomplete_' + id + '_mechanism').texture("kubejs:item/incomplete_" + id + "_mechanism").displayName('Incomplete ' + name + ' Mechanism')
	}
    mechanism('Kinetic')
	mechanism('Sealed')
	mechanism('Infernal', 'UNCOMMON')
	mechanism('Inductive', 'UNCOMMON')
	mechanism('Abstruse', 'RARE')
	mechanism('Calculation', 'EPIC')

    event.create('zinc_dust').texture("kubejs:item/zinc_dust").displayName('Zinc Dust')
	event.create('zinc_sheet').texture("kubejs:item/zinc_sheet").displayName('Zinc Sheet')
    event.create('matter_plastics').texture("kubejs:item/matter_plastics").displayName('Matter Plastics')
	event.create('nickel_compound').texture("kubejs:item/nickel_compound").displayName('Nickel Compound')
    event.create('invar_compound').texture("kubejs:item/invar_compound").displayName('Unprocessed Invar Ingot')
    event.create('flash_drive').texture("kubejs:item/boot_medium").displayName('Flash Drive').maxDamage(512).tooltip('Assembly tool') //assembly tool
	event.create('chromatic_resonator').texture("kubejs:item/chromatic_resonator").displayName('Chromatic Resonator').maxDamage(512).tooltip('Assembly tool')  //assembly tool
	event.create('circuit_scrap').texture("kubejs:item/circuit_scrap").displayName('Circuit Scrap')
	event.create('missingno').texture("kubejs:item/missingno").displayName('∄')
	event.create('screwdriver').texture("kubejs:item/screwdriver").displayName('Screwdriver').maxDamage(512).tooltip('Assembly tool')  //assembly tool
	event.create('iron_saw').texture("kubejs:item/iron_saw").displayName('Iron saw').maxDamage(512).tooltip('Assembly tool')
	event.create('living_core').texture("kubejs:item/living_core").displayName('Living core')
	event.create('mechanical_core').texture("kubejs:item/mechanical_core").displayName('Mechanical core')
	event.create('invar_ingot').texture("kubejs:item/invar_ingot").displayName('Invar ingot')
	event.create('radiant_coil').glow(true).texture("kubejs:item/radiant_coil").displayName('Radiant Induction Coil')
	event.create('radiant_sheet').glow(true).texture("kubejs:item/radiant_sheet").displayName('Radiant Sheet')
	event.create('incomplete_radiant_sheet').glow(true).texture("kubejs:item/incomplete_radiant_sheet").displayName('Incomplete Radiant Sheet')
	event.create('bronze_ingot').texture("kubejs:item/bronze_ingot").displayName('Bronze Ingot')
	event.create('steel_ingot').texture("kubejs:item/steel_ingot").displayName('Steel Ingot')
	event.create('bronze_sheet').texture("kubejs:item/bronze_sheet").displayName('Bronze Sheet')
	event.create('tin_ingot').texture("kubejs:item/tin_ingot").displayName('Tin Ingot')
	event.create('tin_nugget').texture("kubejs:item/tin_nugget").displayName('Tin Nugget')
	event.create('tin_sheet').texture("kubejs:item/tin_sheet").displayName('Tin Sheet')
	event.create('rod_cast').texture("kubejs:item/rod_cast").displayName('Rod Cast')
	event.create('ingot_cast').texture("kubejs:item/ingot_cast").displayName('Ingot Cast')
	event.create('gear_press').texture("kubejs:item/press_gear_die").displayName('Gear Press')
	event.create('sand_ingot_cast').texture("kubejs:item/sand_ingot_cast").displayName('Sand Ingot Cast')
	event.create('sand_rod_cast').texture("kubejs:item/sand_rod_cast").displayName('Sand Rod Cast')
	event.create('cast_ingot').texture("kubejs:item/cast_ingot").displayName('Cast Ingot').maxDamage('4096')
	event.create('coal_dust').texture("kubejs:item/coal_dust").displayName('Coal Dust')
	event.create('overcharged_red_corundum_cluster').texture("kubejs:item/overcharged_red_corundum_cluster").displayName('Overcharged Red Corundum').glow(true)
	event.create('overcharged_blue_corundum_cluster').texture("kubejs:item/overcharged_blue_corundum_cluster").displayName('Overcharged Blue Corundum').glow(true)
	event.create('overcharged_white_corundum_cluster').texture("kubejs:item/overcharged_white_corundum_cluster").displayName('Overcharged White Corundum').glow(true)
	event.create('algal_blend').texture("kubejs:item/algal_blend").displayName('Algal Blend')
	event.create('algal_brick').texture("kubejs:item/algal_brick").displayName('Algal Brick')
	event.create('eternal_ingot').texture("kubejs:item/eternal_ingot").displayName('Eternal Ingot').glow(true)
	event.create('grain_of_infinity').texture("kubejs:item/grain_of_infinity").displayName('Grain of Infinity').glow(true)
	event.create('corundum_dust').texture("kubejs:item/corundum_dust").displayName('Corundum Dust')
	event.create('corundum_seed_1').texture("kubejs:item/corundum_seed_1").displayName('Corundum Seed')
	event.create('corundum_seed_2').texture("kubejs:item/corundum_seed_2").displayName('Corundum Seed')
	event.create('corundum_seed_3').texture("kubejs:item/corundum_seed_3").displayName('Corundum Seed')
})

StartupEvents.registry('block', event => {
    event.create('enderium_casing').model('kubejs:block/enderium_casing').material('metal').hardness(4.0).displayName('Ender Casing')
	event.create('zinc_casing').material('metal').hardness(3.0).displayName('Zinc Casing')
	event.create('invar_casing').material('metal').hardness(3.0).displayName('Invar Casing')
	event.create('fluix_casing').material('metal').hardness(3.0).displayName('Fluix Casing')
	event.create('machine_frame').model('kubejs:block/machine_frame').material('metal').hardness(4.0).displayName('Machine Frame')

    let machine = (name, layer) => {
		let id = name.toLowerCase()
		event.create(id + '_machine')
			.model('kubejs:block/' + id + '_machine')
			.material('lantern')
			.hardness(3.0)
			.displayName(name + ' Machine')
			.notSolid()
			.renderType(layer)
	}

	machine('Andesite', "solid")
	machine('Brass', "translucent")
	machine('Copper', "cutout")
	machine('Zinc', "cutout")
	machine('Enderium', "cutout")
})

StartupEvents.registry('fluid', event => {
	event.create('molten_tin')
		.thickTexture(0xc9c9c9)
		.displayName('Molten Tin')
	event.create('molten_copper')
		.thickTexture(0xe04d11)
		.displayName('Molten Copper')
	event.create('abyssal_blend')
		.thickTexture(0x2f3247)
		.displayName('Abyssal Blend')
})